In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.DataFrame({'x1': [1,2,3,4],'y':[2,4,6,8]})
df.head()

x1  y
0   1  2
1   2  4
2   3  6
3   4  8

In [4]:
x = df[['x1']]
y = df['y']

In [5]:
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [7]:
lr.predict([[5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.])

In [8]:
lr.coef_

array([2.])

In [9]:
lr.intercept_

0.0

In [11]:
lr.score(x,y)*100

100.0

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing

In [24]:
california_data = fetch_california_housing()

In [25]:
california_data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [26]:
df = pd.DataFrame(california_data.data,columns=california_data.feature_names)

In [27]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [28]:
df['price'] = california_data.target

In [29]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [30]:
x = df[[]]
y = df['price']

In [31]:
x = df.drop('price',axis=1)
y = df['price']

In [32]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [34]:
y_pred = model.predict(X_test)

In [35]:
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'price'],
      dtype='object')

In [36]:
model.predict([[8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.15194306])

In [37]:
model.predict(pd.DataFrame({'MedInc':[8.3252],'HouseAge': [41.0],'AveRooms':[6.984127],'AveBedrms': [1.023810],'Population':[322.0],'AveOccup':[2.555556],'Latitude':[37.88],'Longitude':['-122.23']}))

array([4.15194306])

In [30]:
model.score(X_train,y_train)*100

61.255119139669524

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [6]:
df = pd.read_csv('/content/iris.data')
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
df = pd.read_csv('/content/iris.data',header=None,names=['sepal_length','sepal_width','petal_length','petal_width','species'])

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
df.shape

(150, 5)

In [10]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [11]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
lgr = LogisticRegression(max_iter=300)
lgr.fit(X_train,y_train)

LogisticRegression(max_iter=300)

In [14]:
y_pred = lgr.predict(X_test)

In [15]:
accuracy_score(y_test,y_pred)

1.0

In [16]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [18]:
df1 = pd.DataFrame ({'actul values':y_test,'predictvalues':y_pred})

In [19]:
df1

actul values    predictvalues
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [20]:
lgr.predict([[5.1,3.5,1.4,0.2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

In [43]:
df = pd.read_csv('/content/insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [44]:
df ['sex'].unique()

array(['female', 'male'], dtype=object)

In [45]:
df['sex'] = df['sex'].map({'male':1,'female':0})

In [46]:
df.head()


age  sex     bmi  children smoker     region      charges
0   19    0  27.900         0    yes  southwest  16884.92400
1   18    1  33.770         1     no  southeast   1725.55230
2   28    1  33.000         3     no  southeast   4449.46200
3   33    1  22.705         0     no  northwest  21984.47061
4   32    1  28.880         0     no  northwest   3866.85520

In [47]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [48]:
df['smoker'] = df['smoker'].map({'no':0,'yes':1})

In [49]:
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [50]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [51]:
df['region'] = df['region'].map({'southwest':0,'southeast':1,'northwest':2,'northeast':3})

In [54]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       0  16884.92400
1   18    1  33.770         1       0       1   1725.55230
2   28    1  33.000         3       0       1   4449.46200
3   33    1  22.705         0       0       2  21984.47061
4   32    1  28.880         0       0       2   3866.85520

In [55]:
df.shape

(1338, 7)

In [56]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [57]:
df = df.dropna()

In [58]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [59]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [60]:
X = df[['age','sex','bmi', 'children', 'smoker', 'region',]]
y = df['charges']

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
knn = KNeighborsRegressor(n_neighbors=5)

In [64]:
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [66]:
knn.predict([[19,0,27.900,0,1,0.0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([10756.5554])

In [67]:
knn.score(X_train,y_train)

0.3942261378220703

In [68]:
knn.score(X_test,y_test)

0.1463392165684949

In [69]:
dfn = pd.read_csv('/content/insurance.csv')

In [70]:
dfn.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [71]:
dfn.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [72]:
dfn.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [74]:
from sklearn.preprocessing import OneHotEncoder

In [76]:
encoder = OneHotEncoder(sparse=False)
dfn['sex'] = encoder.fit_transform(dfn[['sex']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [77]:
dfn.head()

age  sex     bmi  children smoker     region      charges
0   19  0.0  27.900         0    yes  southwest  16884.92400
1   18  1.0  33.770         1     no  southeast   1725.55230
2   28  1.0  33.000         3     no  southeast   4449.46200
3   33  1.0  22.705         0     no  northwest  21984.47061
4   32  1.0  28.880         0     no  northwest   3866.85520

In [78]:
dfn['smoker'] = encoder.fit_transform(dfn[['smoker']])
dfn['region'] = encoder.fit_transform(dfn[['region']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [79]:
dfn.head()

age  sex     bmi  children  smoker  region      charges
0   19  0.0  27.900         0     0.0     0.0  16884.92400
1   18  1.0  33.770         1     1.0     0.0   1725.55230
2   28  1.0  33.000         3     1.0     0.0   4449.46200
3   33  1.0  22.705         0     1.0     0.0  21984.47061
4   32  1.0  28.880         0     1.0     0.0   3866.85520

In [80]:
dfn.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [82]:
X = dfn[['age','sex','bmi','children','smoker','region']]
y = dfn['charges']

In [85]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [86]:
X_train

age  sex     bmi  children  smoker  region
560    46  0.0  19.950         2     1.0     0.0
1285   47  0.0  24.320         0     1.0     1.0
1142   52  0.0  24.860         0     1.0     0.0
969    39  0.0  34.320         5     1.0     0.0
486    54  0.0  21.470         3     1.0     0.0
...   ...  ...     ...       ...     ...     ...
1095   18  0.0  31.350         4     1.0     1.0
1130   39  0.0  23.870         5     1.0     0.0
1294   58  1.0  25.175         0     1.0     1.0
860    37  0.0  47.600         2     0.0     0.0
1126   55  1.0  29.900         0     1.0     0.0

[1070 rows x 6 columns]

In [87]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [88]:
X_train

array([[ 0.47222651, -1.0246016 , -1.75652513,  0.73433626,  0.50874702,
        -0.57663083],
       [ 0.54331294, -1.0246016 , -1.03308239, -0.91119211,  0.50874702,
         1.73421182],
       [ 0.8987451 , -1.0246016 , -0.94368672, -0.91119211,  0.50874702,
        -0.57663083],
       ...,
       [ 1.3252637 ,  0.97598911, -0.89153925, -0.91119211,  0.50874702,
         1.73421182],
       [-0.16755139, -1.0246016 ,  2.82086429,  0.73433626, -1.96561348,
        -0.57663083],
       [ 1.1120044 ,  0.97598911, -0.10932713, -0.91119211,  0.50874702,
        -0.57663083]])

In [89]:
dfn['charges'][560]

9193.8385

In [90]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [91]:
knn.predict([[0.47222651, -1.0246016 , -1.75652513,  0.73433626,  0.50874702,
        -0.57663083]])

array([8920.43695])

In [92]:
knn.score(X_train,y_train)

0.8701703168118499